CREATE USER springims WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'springims';

GRANT ALL ON TABLE public.flyway_schema_history TO springims;