FROM tomcat:jdk21-temurin
COPY core/target/SpringMVC_IMS.war /usr/local/tomcat/webapps/

# for tryout reasons, you can log in from another container
# RUN apt update && apt -y install postgresql && apt clean